baseurl = "https://yifanchen.io/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Yifan Chen"
title = "Yifan Chen"
pygmentsuseclasses = true
# disqusshortname = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Yifan Chen"
# gravatar = "" # do not use in the same time as Avatar
# avatar = "" # path to image in static dir e.g img/avatar.png (do not use in the same time as Gravatar)
# cachebuster = false # FIXME: See issue #32.
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Software Engineer | Former Management Consultant | MMA Fan"
email = "yifan@yifanchen.io"
faviconfile = "img/favicon.ico"
gatracker = "UA-89463103-1"
googleAnalytics = "UA-89463103-1"
github = "//github.com/yc355"
highlightjs = true
# highlightjslanguages = ["go"] # additional languages not included in the "common" set
initials = "ad" # Displayed on single post page; DEPRECATED in v0.3.0.
lang = "en"
linkedin = "//linkedin.com/in/yifanchen1"
# twitter = "//twitter.com/you"

extracssfiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.
